### ISSUE TITLE
How does the stat multiplier work?

### ISSUE THREAD

**Issue by Reza702** [AnalogMan151/Re-Decode#3]
I was using the plugin, and everything works fine, besides the training stat multiplier. I enable it, but there's no change in the training values. How does it work? And can I change the value if required?

**Comment by AnalogMan151** [comment]
In the plugin with the stat multiplier cheat highlighted tap the keyboard icon on the touch screen to input a multiplier value. It defaults to 1.0x and so if you don't enter your own input then you won't see a change.

**Comment by Reza702** [comment]
So that's what it was. Thanks a bunch!
